# Generated by Django 5.2.4 on 2025-08-15 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueorder',
            old_name='issue',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='subscriptionorder',
            old_name='subscription',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='starts',
            field=models.DateField(default=datetime.datetime(2025, 8, 1, 9, 44, 18, 731181, tzinfo=datetime.timezone.utc)),
        ),
    ]
