# Generated by Django 5.2.4 on 2025-07-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
