# Generated by Django 5.2.4 on 2025-08-20 07:39

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0002_rename_issue_issueorder_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issueorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='issueorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='issueorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='user',
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='starts',
            field=models.DateField(default=datetime.datetime(2025, 8, 1, 7, 38, 57, 397444, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issueorder',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gelv.payment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gelv.payment'),
            preserve_default=False,
        ),
    ]
