# Generated by Django 5.2.4 on 2025-08-20 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0003_remove_issueorder_date_remove_issueorder_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Journal',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='category',
            new_name='journal',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='category',
            new_name='journal',
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='starts',
            field=models.DateField(default=datetime.datetime(2025, 8, 1, 8, 29, 24, 654378, tzinfo=datetime.timezone.utc)),
        ),
    ]
