# Generated by Django 5.2.4 on 2025-08-20 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0004_rename_category_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='starts',
            field=models.DateField(default=datetime.datetime(2025, 8, 1, 8, 34, 18, 275336, tzinfo=datetime.timezone.utc)),
        ),
    ]
