# Generated by Django 5.2.4 on 2025-08-20 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0005_journal_description_alter_issue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='starts',
            field=models.DateField(default=datetime.datetime(2025, 8, 1, 13, 54, 56, 21297, tzinfo=datetime.timezone.utc)),
        ),
    ]
