# Generated by Django 5.2.4 on 2025-08-20 14:00

import gelv.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0006_issue_available_subscription_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorder',
            name='starts',
            field=models.DateField(default=gelv.utils.current_month_year),
        ),
    ]
