# Generated by Django 5.2.4 on 2025-08-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0007_alter_subscriptionorder_starts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='available',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='available',
            new_name='active',
        ),
    ]
