# Generated by Django 5.2.4 on 2025-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0010_user_name_user_personal_code_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='personal_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='shipping_address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
