# Generated by Django 5.2.4 on 2025-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0012_alter_payment_name_alter_payment_personal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='legal_address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='legal_address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
