# Generated by Django 5.2.4 on 2025-08-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0013_payment_legal_address_user_legal_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='personal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='payment',
            name='address_level2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='address_line1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='address_line2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
