# Generated by Django 5.2.4 on 2025-08-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0014_remove_payment_legal_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='address_line2',
        ),
    ]
