# Generated by Django 5.2.4 on 2025-08-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0016_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='address_level2',
            new_name='city',
        ),
    ]
