# Generated by Django 5.2.4 on 2025-08-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0017_rename_address_line1_payment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
