# Generated by Django 5.2.4 on 2025-09-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0019_issue_file_payment_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='anno',
        ),
        migrations.AddField(
            model_name='journal',
            name='frequency',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='starts',
            field=models.IntegerField(),
        ),
    ]
