# Generated by Django 5.2.4 on 2025-09-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0020_remove_journal_anno_journal_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionorder',
            old_name='starts',
            new_name='start',
        ),
    ]
