# Generated by Django 5.2.4 on 2025-09-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0021_rename_starts_subscriptionorder_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
