# Generated by Django 5.2.4 on 2025-09-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0022_issue_discounted_price_subscription_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.FileField(null=True, upload_to='invoices'),
        ),
    ]
