# Generated by Django 5.2.4 on 2025-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0023_payment_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueorder',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='price',
            field=models.FloatField(),
        ),
    ]
