# Generated by Django 5.2.4 on 2025-10-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelv', '0025_ad_rename_active_issue_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
